### ISSUE TITLE
!randomfact crashed with a protocol deprecated error

### ISSUE THREAD

**Issue by odyss3y** [SilenusTA/StreamRoller#10]

**Comment by SilenusTA** [comment]
I'll take a look at that, never seen that error so might be hard to debug. It should at least have a settings page to allow turning it off.

**Comment by SilenusTA** [comment]
Must be tired again, just realized the chat command !randomfact crashes and not the background timer one. Tried it and got the same crash. I'll have a look at it.

-----------------------------
SyntaxError: Unexpected token A in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (file:///C:/repos/Streamroller/extensions/randomfact/randomfact.js:207:34)
-------------------------------

**Comment by SilenusTA** [comment]
There were two errors in this, once I moved it to the new API I found that I had updated the twitchchat extension so the message format internally was wrong.
