### ISSUE TITLE
Chatbot: Channel redemption option

### ISSUE THREAD

**Issue by odyss3y** [SilenusTA/StreamRoller#39]
Have the ability to use channel points to talk directly to the bot.

**Comment by SilenusTA** [comment]
I'll have to check what channel point data I currently have. Might be able to roll it into the work with the subs/followers permissions etc. If not it might have to wait till I get around to doing the Twitch pub/sub extension. Good idea though, might mean there is finally something to use mine on.
Once I get the audio and TTS extension done I could also have paid chatbot TTS :D

**Comment by SilenusTA** [comment]
While working with the chat messages (to try and get things like donations, subs etc forwarded back to chat) I found there is a redeem message that comes in. I need to setup something on stream and test what these messages contain and how to identify/parse them as specific redemptions for chatbot.

Temporarily I should be able to quickly add this (depending on the message I get, I have to be able to identify that it is a redeem for the aichatbot), There is definitely a bigger issue of handling chat (ie a chatbot like nightbot or streamlabs chatbot type features)

Longer term I still haven't decided on how to handle the logic in StreamRoller. Currently it is all hard coded into the LivePortal but this logic is something I want the users to be able to tune themselves easily (that is the main reason for the software after all, I just haven't got to implementing it yet as I needed enough features to work with to be able to figure out a good design for it).

I.e. eventually no one should need to ask for this kind of feature to be added, the idea of StreamRoller is that you would go to a config/logic style page and just set it up by linking the extensions and adding some rules. Until that part is implemented it will never get out of alpha (realistically it should still be in prototype stage but people wanted the chatbot so I though I'd move it to alpha :D)

**Comment by SilenusTA** [comment]
Closing this as I think all these features can now be done using triggers and actions
