### ISSUE TITLE
... for length exceeded is not working

### ISSUE THREAD

**Issue by odyss3y** [SilenusTA/StreamRoller#5]

**Comment by SilenusTA** [comment]
I forget which issue this was now. The lack of sleep during the stream means I don't remember much what we talked about lol (ended up being 37 between sleeps lol)

**Comment by odyss3y** [comment]
this was where "..." wasnt being used when the openai returned an error for length.

**Comment by SilenusTA** [comment]
Haha I read the issue title literally. ie as a ... in the message such that you were extending another issue :D 
Should be fixed, need to test though.
