### ISSUE TITLE
Pipe random facts through chatbot to help keep chat alive

### ISSUE THREAD

**Issue by SilenusTA** [SilenusTA/StreamRoller#57]
Using the random facts action it would be nice to be able to use them to seed the conversation via the chatbot. Need to add a chatbot action that can take in a message for seeding to do it.

**Comment by odyss3y** [comment]
this gets into another feature centered around the variables from other modules being available to others. for example, random fact can be triggered on timer/macro/etc to update, the update itself can trigger chatbot to reply. in this same way it would be useful for the msfs module simvars to be exposed as well. if streamroller knows through simvars where the plane is, it can come up with something interesting about that even just using the lat/long.

**Comment by odyss3y** [comment]
another example: chatbot could generate something to say based on the stream category and the uptime

**Comment by odyss3y** [comment]
overlap https://github.com/SilenusTA/StreamRoller/issues/57
