### ISSUE TITLE
Trigger to change chatbot profile and respond fails

### ISSUE THREAD

**Issue by odyss3y** [SilenusTA/StreamRoller#69]
two triggers for each action, fails with:
!!! ERROR !!! [EXTENSION]twitchchat ["Twitch.say error","Cannot read properties of undefined (reading 'startsWith')"]

**Comment by odyss3y** [comment]
it is getting so far as going to openai and getting the response as well

**Comment by SilenusTA** [comment]
Interesting, ill see if I can replicate it
