### ISSUE TITLE
Trigger to change chatbot profile fails

### ISSUE THREAD

**Issue by odyss3y** [SilenusTA/StreamRoller#70]
`!!! ERROR !!! [EXTENSION]chatbot.onDataCenterMessage ["chatbot profle","Normal","doesn't exist"]`

https://github.com/SilenusTA/StreamRoller/blob/59b2562979d29f7739237bda9f48ad953c9f19ca/extensions/chatbot/chatbot.js#L435

**Comment by SilenusTA** [comment]
Seems to work ok in latest release, I had to re-do the trigger though as the change to allow 'start of line' or 'anywhere' means that the old trigger had reset to match exactly.
