### ISSUE TITLE
Autopilot Edit Function Unescaped Chars Issue

### ISSUE THREAD

**Issue by odyss3y** [SilenusTA/StreamRoller#78]
Editing trigger with a character that needs escaped like ' or " are causing the edit load function to be cut off.

This is the 'original' trigger parameter example.

would only load as:

This is the

**Comment by SilenusTA** [comment]
Fixed. the single quote issue but it introduced a double quote issue so need to go through and fix them all properly.

**Comment by SilenusTA** [comment]
Fixed single quotes but now have double quote issues. ill go through and fix it all properly :(
